# Generated by Django 6.0.1 on 2026-01-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_patient_patient_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='payment_amount',
        ),
        migrations.AddField(
            model_name='patient',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card')], max_length=20, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='membership_plan',
            field=models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], max_length=20, null=True, verbose_name='Membership Plan'),
        ),
    ]
