# Generated by Django 6.0.1 on 2026-01-09 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0004_remove_patient_payment_amount_patient_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('type', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS')], default='Email', max_length=10, verbose_name='Type')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email Subject')),
                ('body', models.TextField(help_text='Use placeholders like {first_name}, {last_name}, {next_birthday}', verbose_name='Message Body')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(verbose_name='Scheduled For')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('cc_recipients', models.CharField(blank=True, help_text='Comma separated emails', max_length=500, null=True)),
                ('bcc_recipients', models.CharField(blank=True, help_text='Comma separated emails', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_wishes', to='birthday.patient')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='birthday.messagetemplate')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
    ]
