# Generated by Django 6.0.1 on 2026-01-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_messagetemplate_scheduledwish'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Recipient Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('recipient_type', models.CharField(choices=[('CC', 'CC'), ('BCC', 'BCC')], default='CC', max_length=5)),
                ('is_default', models.BooleanField(default=False, verbose_name='Select by Default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
