# Generated by Django 6.0.1 on 2026-01-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0007_patientstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstatus',
            name='full_content',
            field=models.TextField(blank=True, help_text='Full detail (e.g., Email Body)', null=True),
        ),
        migrations.AlterField(
            model_name='patientstatus',
            name='description',
            field=models.TextField(blank=True, help_text='Brief summary (e.g., Email Subject)', null=True),
        ),
    ]
