# Generated by Django 6.0.1 on 2026-01-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0008_patientstatus_full_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='signature',
            field=models.TextField(blank=True, null=True, verbose_name='Email Signature (HTML)'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='body',
            field=models.TextField(help_text='Use placeholders like {first_name}, {last_name}', verbose_name='Message Body'),
        ),
    ]
