# Generated by Django 6.0.1 on 2026-01-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0011_patient_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledwish',
            name='custom_body',
            field=models.TextField(blank=True, null=True, verbose_name='Custom Body'),
        ),
        migrations.AddField(
            model_name='scheduledwish',
            name='custom_subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Custom Subject'),
        ),
    ]
