# Generated by Django 6.0.1 on 2026-01-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0013_planhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
