# Generated by Django 6.0.1 on 2026-01-30 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0014_patient_gender_patient_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True, verbose_name='SMO Practice ID')),
                ('name', models.CharField(max_length=200, verbose_name='Practice Name')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='External ID (SMO)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='birthday.practice'),
        ),
    ]
