# Generated by Django 6.0.1 on 2026-02-02 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0016_practice_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Plan Name')),
                ('tier', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], max_length=20, unique=True, verbose_name='Plan Tier')),
                ('annual_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Annual Price ($)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Plan Description')),
                ('included_services', models.JSONField(blank=True, default=list, help_text='List of services included at no extra charge', verbose_name='Included Services')),
                ('preventive_discount', models.IntegerField(default=0, verbose_name='Preventive Discount (%)')),
                ('restorative_discount', models.IntegerField(default=0, verbose_name='Restorative Discount (%)')),
                ('cosmetic_discount', models.IntegerField(default=0, verbose_name='Cosmetic Discount (%)')),
                ('implant_discount', models.IntegerField(default=0, verbose_name='Implant Discount (%)')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='Display Color (Hex)')),
                ('icon', models.CharField(default='bi-star', max_length=50, verbose_name='Bootstrap Icon Class')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Plan')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Plan',
                'verbose_name_plural': 'Membership Plans',
                'ordering': ['display_order', 'tier'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_name', models.CharField(default='Implants Guru', max_length=200, verbose_name='Practice Name')),
                ('practice_phone', models.CharField(default='760-340-5107', max_length=20, verbose_name='Practice Phone')),
                ('practice_email', models.EmailField(default='info@implantsguru.dentist', max_length=254, verbose_name='Practice Email')),
                ('practice_address', models.TextField(blank=True, null=True, verbose_name='Practice Address')),
                ('practice_website', models.URLField(default='https://www.implantsguru.dentist', verbose_name='Website')),
                ('reinstatement_fee', models.DecimalField(decimal_places=2, default=50.0, max_digits=6, verbose_name='Reinstatement Fee ($)')),
                ('grace_period_days', models.IntegerField(default=30, verbose_name='Grace Period (Days)')),
                ('plan_duration_days', models.IntegerField(default=365, verbose_name='Plan Duration (Days)')),
                ('enrollment_base_url', models.URLField(default='https://portal.sivahub.com/SivaForms/SecuredForms/ClientHTMLForms/1864/Dental-Savings-Membership-Plan', verbose_name='Enrollment Form URL')),
                ('from_email', models.EmailField(default='noreply@implantsguru.dentist', max_length=254, verbose_name='From Email')),
                ('reply_to_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Reply-To Email')),
                ('sms_enabled', models.BooleanField(default=True, verbose_name='SMS Enabled')),
                ('sms_sender_name', models.CharField(default='ImplantsGuru', max_length=20, verbose_name='SMS Sender Name')),
                ('auto_birthday_wishes', models.BooleanField(default=True, verbose_name='Auto Birthday Wishes')),
                ('auto_renewal_reminders', models.BooleanField(default=True, verbose_name='Auto Renewal Reminders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Practice Settings',
                'verbose_name_plural': 'Practice Settings',
            },
        ),
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Service Name')),
                ('category', models.CharField(choices=[('Preventive', 'Preventive'), ('Restorative', 'Restorative'), ('Cosmetic', 'Cosmetic'), ('Implant', 'Implant'), ('Other', 'Other')], max_length=50, verbose_name='Category')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Regular Price ($)')),
                ('bronze_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bronze Price ($)')),
                ('silver_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Silver Price ($)')),
                ('gold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Gold Price ($)')),
                ('included_in_bronze', models.BooleanField(default=False, verbose_name='Included in Bronze')),
                ('included_in_silver', models.BooleanField(default=False, verbose_name='Included in Silver')),
                ('included_in_gold', models.BooleanField(default=False, verbose_name='Included in Gold')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Pricing',
                'verbose_name_plural': 'Service Pricing',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Campaign Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('trigger_type', models.CharField(choices=[('birthday', 'Birthday (On Day)'), ('birthday_before', 'Birthday (Days Before)'), ('expiring_30', 'Plan Expiring in 30 Days'), ('expiring_14', 'Plan Expiring in 14 Days'), ('expiring_7', 'Plan Expiring in 7 Days'), ('expired', 'Plan Just Expired'), ('grace_ending', 'Grace Period Ending (25 Days)'), ('anniversary', 'Membership Anniversary'), ('upgrade_promo', 'Upgrade Promotion'), ('welcome', 'Welcome New Member'), ('manual', 'Manual Trigger Only')], max_length=50, verbose_name='Trigger Type')),
                ('days_before', models.IntegerField(default=0, help_text='For birthday_before trigger, how many days before', verbose_name='Days Before Event')),
                ('send_time', models.TimeField(default='09:00', verbose_name='Send Time')),
                ('target_plans', models.JSONField(blank=True, default=list, help_text="Leave empty for all plans, or specify ['Bronze', 'Silver', 'Gold']", verbose_name='Target Plans')),
                ('target_patient_type', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Proceed', 'Proceed')], max_length=20, null=True, verbose_name='Target Patient Type')),
                ('channel', models.CharField(choices=[('Email', 'Email Only'), ('SMS', 'SMS Only'), ('Both', 'Email & SMS')], default='Email', max_length=20, verbose_name='Channel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('total_sent', models.IntegerField(default=0, verbose_name='Total Sent')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Last Run')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns', to='birthday.messagetemplate', verbose_name='Email Template')),
                ('sms_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_campaigns', to='birthday.messagetemplate', verbose_name='SMS Template')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['trigger_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('patients_targeted', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('sms_sent', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='birthday.campaign')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS')], max_length=20)),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('recipient', models.CharField(max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='birthday.campaign')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='birthday.patient')),
            ],
            options={
                'verbose_name': 'Communication Log',
                'verbose_name_plural': 'Communication Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
