# Generated by Django 6.0.1 on 2026-02-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0017_membershipplan_practicesettings_servicepricing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='accepts_marketing',
            field=models.BooleanField(default=True, verbose_name='Accepts Communications'),
        ),
        migrations.AddField(
            model_name='patient',
            name='unsubscribe_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Unsubscribe Reason'),
        ),
        migrations.AddField(
            model_name='patient',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Unsubscribed Date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='patientstatus',
            name='activity_type',
            field=models.CharField(choices=[('Added', 'Patient Added'), ('Email Sent', 'Email Sent'), ('SMS Sent', 'SMS Sent'), ('Plan Updated', 'Plan Updated'), ('Details Updated', 'Details Updated'), ('Opt-out', 'Communication Opt-out'), ('Opt-in', 'Communication Opt-in')], max_length=50),
        ),
    ]
