# Generated by Django 6.0.1 on 2026-02-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0018_patient_accepts_marketing_patient_unsubscribe_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledwish',
            name='channel',
            field=models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS')], default='Email', max_length=10),
        ),
    ]
