# Generated by Django 6.0.1 on 2026-01-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_alter_patient_address_alter_patient_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Proceed', 'Proceed (In-house Plan)')], default='Regular', max_length=20, verbose_name='Patient Type'),
        ),
    ]
