# Generated by Django 6.0.1 on 2026-01-09 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0006_savedrecipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Added', 'Patient Added'), ('Email Sent', 'Email Sent'), ('SMS Sent', 'SMS Sent'), ('Plan Updated', 'Plan Updated'), ('Details Updated', 'Details Updated')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='birthday.patient')),
            ],
            options={
                'verbose_name_plural': 'Patient Statuses',
                'ordering': ['-created_at'],
            },
        ),
    ]
