# Generated by Django 6.0.1 on 2026-01-09 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0009_messagetemplate_signature_alter_messagetemplate_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Signature Name')),
                ('content', models.TextField(verbose_name='Signature Content (HTML)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Signature')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='birthday.emailsignature', verbose_name='Default Signature'),
        ),
    ]
