# Generated by Django 6.0.1 on 2026-01-21 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0012_scheduledwish_custom_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_plan', models.CharField(max_length=20)),
                ('new_plan', models.CharField(max_length=20)),
                ('change_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_history', to='birthday.patient')),
            ],
            options={
                'verbose_name_plural': 'Plan History',
                'ordering': ['-created_at'],
            },
        ),
    ]
