# Generated by Django 6.0.1 on 2026-01-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0015_practice_patient_external_id_patient_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='client_id',
            field=models.CharField(default='1', max_length=50, verbose_name='SMO Client ID'),
        ),
    ]
